gesdinet_jwt_refresh_token:
  path:     /api/token/refresh
  defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }
#app_directory:
#    # loads routes from the YAML or XML files found in that directory
#    resource: '../src/Portmone/Resources/config'
#    type:     directory
#
